Repository webex/webex-js-sdk, pull requests merged in 2022-01, with the labels that each got.

#2261 docs(plugin-meeting): update samples meetings management
  packages/node_modules/samples/browser-plugin-meetings/app.js
  packages/node_modules/samples/browser-plugin-meetings/index.html
  packages/node_modules/samples/browser-plugin-meetings/style.css
  packages/node_modules/samples/browser-plugin-meetings/test/wdio/spec/mediatest.js
Labels: ready to merge

#2274 fix(plugin-meetings): use icegatheringstatechange for ice completed
  packages/node_modules/@webex/plugin-meetings/src/common/errors/webex-errors.js
  packages/node_modules/@webex/plugin-meetings/src/constants.js
  packages/node_modules/@webex/plugin-meetings/src/peer-connection-manager/index.js
  packages/node_modules/@webex/plugin-meetings/test/unit/spec/peerconnection-manager/index.js
Labels: bug-fix

#2276 docs(plugin-meeting): update samples device management
  packages/node_modules/samples/browser-plugin-meetings/index.html
Labels: docs

#2280 docs(plugin-meetings): add fix for device button handler
  packages/node_modules/samples/browser-plugin-meetings/app.js
Labels: docs

#2277 docs(plugin-meeting): update samples authentication
  packages/node_modules/samples/browser-plugin-meetings/app.js
  packages/node_modules/samples/browser-plugin-meetings/index.html
  packages/node_modules/samples/browser-plugin-meetings/style.css
  packages/node_modules/samples/browser-plugin-meetings/test/wdio/spec/mediatest.js
Labels: docs
