Repository webex/webex-js-sdk, pull requests merged in 2024-09, with the labels that each got.

#3799 feat(internal-plugin-metrics): add more verbs to taxonomy for behavioral metrics
  packages/@webex/internal-plugin-metrics/src/metrics.types.ts
Labels: validated

#3802 fix: availableBitrate in media-core
  packages/@webex/media-helpers/package.json
  packages/@webex/plugin-meetings/package.json
  packages/calling/package.json
  yarn.lock
Labels: validated

#3803 fix(plugin-meetings): clientSignallingProtocol stat
  packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts
  packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts
Labels: validated

#3797 fix(audio-mute): fix sometimes out-of-sync remote audio mute
  packages/@webex/plugin-meetings/src/locus-info/selfUtils.ts
  packages/@webex/plugin-meetings/src/meeting/muteState.ts
  packages/@webex/plugin-meetings/test/unit/spec/locus-info/selfUtils.js
  packages/@webex/plugin-meetings/test/unit/spec/meeting/muteState.js
Labels: validated

#3810 docs(byods): added initial readme file for byods
  packages/byods/README.md
Labels: validated

#3806 fix: update internal media core version
  packages/@webex/media-helpers/package.json
  packages/@webex/plugin-meetings/package.json
  packages/calling/package.json
  yarn.lock
Labels: validated

#3808 fix(plugin-meetings): add to peer connection bare turn tcp server
  packages/@webex/plugin-meetings/src/media/index.ts
  packages/@webex/plugin-meetings/test/unit/spec/media/index.ts
  packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Labels: validated

#3811 feat(byods): project setup
  package.json
  packages/byods/.gitignore
  packages/byods/babel.config.json
  packages/byods/package.json
  packages/byods/src/BYODS.ts
  packages/byods/src/apiClient.ts
  packages/byods/src/index.ts
  packages/byods/tsconfig.json
  yarn.lock
Labels: validated

#3814 fix: update internal media core
  packages/@webex/media-helpers/package.json
  packages/@webex/plugin-meetings/package.json
  packages/calling/package.json
  yarn.lock
Labels: validated

#3819 feat(contacts): move contacts to scim from dss
  docs/samples/calling/app.js
  packages/calling/src/CallingClient/calling/CallerId/types.ts
  packages/calling/src/CallingClient/constants.ts
  packages/calling/src/Contacts/ContactsClient.test.ts
  packages/calling/src/Contacts/ContactsClient.ts
  packages/calling/src/Contacts/constants.ts
  packages/calling/src/Contacts/contactFixtures.ts
  packages/calling/src/Contacts/types.ts
  packages/calling/src/SDKConnector/types.ts
  packages/calling/src/common/Utils.test.ts
  packages/calling/src/common/Utils.ts
  packages/calling/src/common/constants.ts
  packages/calling/src/common/testUtil.ts
  packages/calling/src/common/types.ts
  packages/webex/src/calling.js
Labels: validated

#3821 feat(byods): Spark 549034 jest setup
  packages/byods/jest.config.js
  packages/byods/jest.d.ts
  packages/byods/jest.setup.js
  packages/byods/package.json
  packages/byods/src/BYODS.ts
  packages/byods/src/BYoDS.test.ts
  packages/legacy/tools/src/models/package/package.constants.ts
  packages/legacy/tools/src/models/package/package.ts
  yarn.lock
Labels: validated

#3823 fix(meetings): sending ice candidate errors with add media success metric
  packages/@webex/plugin-meetings/src/meeting/index.ts
  packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
Labels: validated

#3827 fix(contacts): handle optional scim fields
  packages/calling/src/Contacts/ContactsClient.test.ts
  packages/calling/src/Contacts/ContactsClient.ts
  packages/calling/src/Contacts/contactFixtures.ts
  packages/calling/src/Contacts/types.ts
  packages/calling/src/common/Utils.test.ts
  packages/calling/src/common/Utils.ts
  packages/calling/src/common/testUtil.ts
  packages/calling/src/common/types.ts
Labels: validated

#3829 fix(contacts): fix loop and use only resolved contacts from scim
  packages/calling/src/Contacts/ContactsClient.ts
Labels: validated

#3834 fix(contacts): use webexapis.com url to avoid cors
  packages/calling/src/CallSettings/UcmBackendConnector.test.ts
  packages/calling/src/CallSettings/UcmBackendConnector.ts
  packages/calling/src/CallSettings/constants.ts
  packages/calling/src/Contacts/ContactsClient.test.ts
  packages/calling/src/common/Utils.test.ts
  packages/calling/src/common/Utils.ts
  packages/calling/src/common/constants.ts
Labels: validated

#3830 fix(meetings): empty webrtc dumps when user closes the browser early
  packages/@webex/plugin-meetings/src/rtcMetrics/index.ts
  packages/@webex/plugin-meetings/test/unit/spec/rtcMetrics/index.ts
Labels: validated

#3804 docs(samples): add support for locus calls and resolve join button issue
  docs/samples/browser-plugin-meetings/app.js
  docs/samples/browser-plugin-meetings/index.html
Labels: validated

#3832 Upstreamsvcs
  packages/@webex/internal-plugin-device/src/config.js
  packages/@webex/internal-plugin-device/src/device.js
  packages/@webex/internal-plugin-device/test/unit/spec/device.js
Labels: validated

#3813 fix(plugin-meetings): add retry mechanism to fetching clusters
  packages/@webex/plugin-meetings/src/reachability/index.ts
  packages/@webex/plugin-meetings/test/unit/spec/reachability/index.ts
Labels: validated

#3838 feat(meetings): do ip version detection in parallel with reachability
  packages/@webex/plugin-meetings/src/reachability/index.ts
  packages/@webex/plugin-meetings/test/unit/spec/reachability/index.ts
Labels: validated

#3805 feat(calling): update failover logic for cc
  packages/calling/src/CallingClient/constants.ts
  packages/calling/src/CallingClient/registration/register.test.ts
  packages/calling/src/CallingClient/registration/register.ts
Labels: validated

#3816 feat(callhistory): add-support-for-multiline-in-callhistory
  packages/calling/src/CallHistory/CallHistory.test.ts
  packages/calling/src/CallHistory/CallHistory.ts
  packages/calling/src/CallHistory/callHistoryFixtures.ts
  packages/calling/src/CallHistory/constants.ts
  packages/calling/src/CallHistory/types.ts
  packages/calling/src/Events/types.ts
  packages/calling/src/common/Utils.ts
Labels: validated

#3824 feat(byods): create the main BYODS class implementation
  packages/byods/jest.config.js
  packages/byods/package.json
  packages/byods/src/BYODS.ts
  packages/byods/src/BYoDS.test.ts
  packages/byods/src/apiClient.ts
  packages/byods/src/base-client/index.ts
  packages/byods/src/byods/index.ts
  packages/byods/src/constants.ts
  packages/byods/src/data-source-client/constants.ts
  packages/byods/src/data-source-client/index.ts
  packages/byods/src/data-source-client/types.ts
  packages/byods/src/http-client/types.ts
  packages/byods/src/index.ts
  packages/byods/src/token-manager/index.ts
  packages/byods/src/types.ts
  packages/byods/test/unit/spec/base-client/index.ts
  packages/byods/test/unit/spec/byods/index.ts
  packages/byods/test/unit/spec/data-source-client/index.ts
  packages/byods/test/unit/spec/token-manager/index.ts
  packages/byods/tsconfig.json
  yarn.lock
Labels: validated

#3818 Operational buisness metrics
  packages/@webex/internal-plugin-metrics/src/behavioral-metrics.ts
  packages/@webex/internal-plugin-metrics/src/behavioral/behavioral-metrics.ts
  packages/@webex/internal-plugin-metrics/src/behavioral/config.ts
  packages/@webex/internal-plugin-metrics/src/business-metrics.ts
  packages/@webex/internal-plugin-metrics/src/generic-metrics.ts
  packages/@webex/internal-plugin-metrics/src/index.ts
  packages/@webex/internal-plugin-metrics/src/metrics.types.ts
  packages/@webex/internal-plugin-metrics/src/new-metrics.ts
  packages/@webex/internal-plugin-metrics/src/operational-metrics.ts
  packages/@webex/internal-plugin-metrics/test/unit/spec/behavioral/behavioral-metrics.ts
  packages/@webex/internal-plugin-metrics/test/unit/spec/business/business-metrics.ts
  packages/@webex/internal-plugin-metrics/test/unit/spec/operational/operational-metrics.ts
Labels: validated

#3848 feat(contacts): add the resolved field to contacts
  packages/calling/src/Contacts/ContactsClient.test.ts
  packages/calling/src/Contacts/ContactsClient.ts
  packages/calling/src/Contacts/types.ts
Labels: validated

#3847 feat(presence-plugin): pass label to aphelia API whilst setting status
  packages/@webex/internal-plugin-presence/src/presence.js
  packages/@webex/internal-plugin-presence/test/integration/spec/presence.js
  packages/@webex/internal-plugin-presence/test/unit/spec/presence.js
  packages/@webex/plugin-presence/src/presence.ts
  packages/@webex/plugin-presence/test/integration/spec/presence.ts
  packages/@webex/plugin-presence/test/unit/spec/presence.ts
Labels: validated

#3850 fix(meetings): added reachability trigger to metrics
  packages/@webex/plugin-meetings/src/meetings/index.ts
  packages/@webex/plugin-meetings/src/reachability/index.ts
  packages/@webex/plugin-meetings/src/reconnection-manager/index.ts
  packages/@webex/plugin-meetings/test/unit/spec/meetings/index.js
  packages/@webex/plugin-meetings/test/unit/spec/reachability/index.ts
Labels: validated

#3845 fix(media-effects): include fix for sluggy video in background tab
  docs/samples/browser-plugin-meetings/app.js
  packages/@webex/media-helpers/package.json
  yarn.lock
Labels: validated

#3854 fix(meetings): webex.internal.device doesn't know when user is in a meeting
  packages/@webex/plugin-meetings/src/meeting/index.ts
  packages/@webex/plugin-meetings/src/meeting/util.ts
  packages/@webex/plugin-meetings/test/unit/spec/meeting/index.js
  packages/@webex/plugin-meetings/test/unit/spec/meeting/utils.js
  packages/@webex/test-helper-mock-webex/src/index.js
Labels: validated

#3862 fix: update internal-media-core with conditional device permissions fix
  packages/@webex/media-helpers/package.json
  packages/@webex/plugin-meetings/package.json
  packages/calling/package.json
  yarn.lock
Labels: validated

#3856 feat(ca-metrics): allow override of buildType when running e2e tests against prod
  packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.util.ts
  packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.util.ts
Labels: validated

#3867 fix(voicemail): process check in metrics for voicemail
  packages/calling/src/Metrics/index.ts
Labels: bug-fix, validated, calling

#3865 feat(metrics): add session correlation id identifier
  packages/@webex/internal-plugin-metrics/package.json
  packages/@webex/internal-plugin-metrics/src/call-diagnostic/call-diagnostic-metrics.ts
  packages/@webex/internal-plugin-metrics/src/metrics.types.ts
  packages/@webex/internal-plugin-metrics/test/unit/spec/call-diagnostic/call-diagnostic-metrics.ts
  yarn.lock
Labels: validated

#3839 SPARK-351232 - Add timers to handle missed events during a call
  packages/calling/src/CallingClient/calling/call.test.ts
  packages/calling/src/CallingClient/calling/call.ts
Labels: validated

#3872 fix(voicemail): process-check-for-ms-teams-integration
  packages/calling/src/Metrics/index.ts
Labels: external, validated, calling

#3857 feat(byods): added verify jws token api
  packages/byods/src/byods/index.ts
  packages/byods/src/types.ts
  packages/byods/test/unit/spec/byods/index.ts
Labels: validated
